# Generated by Django 3.1.5 on 2021-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
